spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:apm-database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle
      driver-class-name: org.h2.Driver
      username: sa
      password: 
  flyway:
    locations:
    - classpath:db/migration
    sql-migration-prefix: APM_
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher